modLoader="javafml"
loaderVersion="[47,)" # 47.x.x is Forge 1.20.1
license="MIT"
issueTrackerURL="https://github.com/yourusername/yourmod/issues"

[[mods]]
modId="vsiacompatmod"
version="1.0.0"
displayName="VSIA Compat Mod"
description='''
A compat mod that makes VS physics and Immerse Aircrafts compatible
'''

authors="RSlover521"